#ifndef CORE_H_
#define CORE_H_

#include <stdint.h>

#include "eval.h"
#include "types.h"

enum intrinsic_id {
  INTRINSIC_FN_START = 0,

  INTRINSIC_IS_INTEGER = INTRINSIC_FN_START,
  INTRINSIC_TO_INT,
  INTRINSIC_INT_ADD,
  INTRINSIC_INT_SUB,
  INTRINSIC_INT_MUL,
  INTRINSIC_INT_DIV,
  INTRINSIC_INT_BITAND,
  INTRINSIC_INT_BITOR,
  INTRINSIC_INT_BITXOR,
  INTRINSIC_INT_BITSHIFT,

  INTRINSIC_INT_LT,
  INTRINSIC_INT_LTE,
  INTRINSIC_INT_GT,
  INTRINSIC_INT_GTE,
  INTRINSIC_INT_EQ,

  INTRINSIC_IS_REAL,
  INTRINSIC_TO_REAL,
  INTRINSIC_REAL_ADD,
  INTRINSIC_REAL_SUB,
  INTRINSIC_REAL_MUL,
  INTRINSIC_REAL_DIV,
  INTRINSIC_REAL_LT,
  INTRINSIC_REAL_LTE,
  INTRINSIC_REAL_GT,
  INTRINSIC_REAL_GTE,
  INTRINSIC_REAL_EQ,

  INTRINSIC_REAL_EXP,
  INTRINSIC_REAL_LOG,
  INTRINSIC_REAL_POW,

  // TODO Get consistent set of equality checks. Current setup is:
  // - =: compares by reference. Works for integers and symbols due to how
  // they are implemented
  // - equal?: structural comparison, working for strings and lists
  // TODO Make equality checks variadic (this one and others)?
  INTRINSIC_IDENTICAL,
  INTRINSIC_STRING_TO_SYMBOL,
  INTRINSIC_IS_SYMBOL,
  INTRINSIC_IS_FUNCTION,
  INTRINSIC_FUNCTION_NAME,
  INTRINSIC_IS_NULL,
  INTRINSIC_MAKE_CONS,
  INTRINSIC_IS_CONS,
  INTRINSIC_CAR,
  INTRINSIC_CDR,

  INTRINSIC_IS_CHAR,
  // TODO Impl char comparisions via char->int?
  INTRINSIC_CHAR_LT,
  INTRINSIC_CHAR_LTE,
  INTRINSIC_CHAR_GT,
  INTRINSIC_CHAR_GTE,
  INTRINSIC_CHAR_EQ,
  INTRINSIC_CHAR_TO_INT,
  INTRINSIC_INT_TO_CHAR,

  INTRINSIC_IS_STRING,
  INTRINSIC_STRING_EQ,
  INTRINSIC_STRING_COUNT,
  INTRINSIC_STRING_GET,
  INTRINSIC_STRING_CONCAT,
  INTRINSIC_TO_STRING,

  INTRINSIC_IS_ATOM,
  INTRINSIC_MAKE_ATOM,
  INTRINSIC_DEREF,
  INTRINSIC_RESET,

  INTRINSIC_IS_ARRAY,
  INTRINSIC_MAKE_ARRAY,
  INTRINSIC_ARRAY_LENGTH,
  INTRINSIC_ARRAY_GET,
  INTRINSIC_ARRAY_SET,

  INTRINSIC_READ_STR,
  INTRINSIC_WRITE,
  INTRINSIC_WRITE_STR,
  INTRINSIC_DISPLAY,
  INTRINSIC_NEWLINE,
  INTRINSIC_FLUSH,
  INTRINSIC_SLURP,
  INTRINSIC_LOAD_FILE,
  INTRINSIC_RAISE,
  INTRINSIC_BACKTRACE,
  INTRINSIC_RUNTIME,
  INTRINSIC_TIME_MS,
  INTRINSIC_SLEEP,

  INTRINSIC_MACROEXPAND_1,
  INTRINSIC_DISASSEMBLE,

  INTRINSIC_FN_END,
  INTRINSIC_INTERNAL_START = INTRINSIC_FN_END,

  INTRINSIC_PERPARE_APPLY = INTRINSIC_INTERNAL_START,
  INTRINSIC_COMPILE_TO_CLOSURE,

  INTRINSIC_INVALID,
};

static_assert(INTRINSIC_INVALID <= UINT8_MAX, "too many intrinsics");

enum eval_status call_intrinsic(uint8_t index, struct lisp_vm *vm);
void define_builtins(struct lisp_env *global_env);

#endif
